# Generated by Django 1.11.14 on 2018-07-15 00:03
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("sites", "0002_alter_domain_unique")]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "drafted"), (2, "published"), (3, "removed")],
                        db_index=True,
                        default=1,
                        help_text='Only objects with             "published" status will be displayed publicly.',
                        verbose_name="status",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="question")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in         the URL for the Question. Must be unique.",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                ("answer", models.TextField(verbose_name="answer")),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="An integer used to order the question             amongst others related to the same topic. If not given this             question will be last in the list.",
                        verbose_name="ordering",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ("ordering", "question", "slug"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "drafted"), (2, "published"), (3, "removed")],
                        db_index=True,
                        default=1,
                        help_text='Only objects with             "published" status will be displayed publicly.',
                        verbose_name="status",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in         the URL for the topic. Must be unique.",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A short description of this topic.",
                        verbose_name="description",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="An integer used to order the topic             amongst others. If not given this             topic will be last in the list.",
                        verbose_name="ordering",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        related_name="faq_topics", to="sites.Site", verbose_name="sites"
                    ),
                ),
            ],
            options={
                "verbose_name": "topic",
                "verbose_name_plural": "topics",
                "ordering": ("ordering", "title", "slug"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="faq.Topic",
                verbose_name="topic",
            ),
        ),
    ]
