# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 18:40
from __future__ import unicode_literals

from django.db import migrations


def make_many_map_types(apps, schema_editor):
    """
        Adds the MapType object in Map.map_type to the
        many-to-many relationship in Map.map_types
    """
    Map = apps.get_model('race', 'Map')

    for _map in Map.objects.all():
        _map.map_types.add(_map.map_type)


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_map_map_types'),
    ]

    operations = [
        migrations.RunPython(make_many_map_types),
    ]
