# Generated by Django 1.9.1 on 2016-01-29 01:31
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("race", "0003_auto_20160128_1840")]

    operations = [migrations.RemoveField(model_name="map", name="map_type")]
