# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0004_remove_map_map_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='video',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_connection_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
