# Generated by Django 1.11.14 on 2018-07-11 22:23
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("race", "0005_auto_20160821_1602")]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="video",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Must be a youtube link like https://www.youtube.com/watch?v=32udz2uuwrew3u",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.TextField(blank=True, help_text="You may use Markdown syntax"),
        ),
        migrations.AlterField(
            model_name="server",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this server should be treated as active. Unselect this instead of deleting servers.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="maintained_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintained_servers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="maintainer",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="name",
            field=models.CharField(max_length=100, verbose_name="server name"),
        ),
    ]
