# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
