# Generated by Django 1.11.14 on 2018-07-11 22:23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="content",
            field=models.TextField(help_text="You may use Markdown syntax"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="excerpt",
            field=models.TextField(blank=True, help_text="You may use Markdown syntax"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="is_micro",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this entry should be displayed as micropost. It will not be included in Teeplanet feed.",
                verbose_name="micro",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Published"), (2, "Draft"), (3, "Hidden")], default=2
            ),
        ),
    ]
